### ISSUE TITLE
Completely destroys our test cases now..

### ISSUE THREAD

**Issue by Wavfact** [Tealium/integration-angularjs#21]
With the latest update (worked fine on v1.1.1), Getting:

Error: [$injector:modulerr] Failed to instantiate module TealiumHelper due to:
        Error: [$injector:nomod] Module 'TealiumHelper' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by Wavfact** [comment]
I am not understanding the logic behind combining the 3 files into one?  

Define 1 component per file, recommended to be less than 400 lines of code.
Why?: One component per file promotes easier unit testing and mocking.
Why?: One component per file makes it far easier to read, maintain, and avoid collisions with teams in source control.
Why?: One component per file avoids hidden bugs that often arise when combining components in a file where they may share variables, create unwanted closures, or unwanted coupling with dependencies.

**Comment by tygavin** [comment]
@Wavfact You're a better man than me to have test cases that fail with changes.  :-) We'll get those in tests in here too at some point.

This was my reason to combine the files:
https://github.com/Tealium/integration-angularjs/issues/12
"better gzip benefit and fewer HTTP requests for those who just use out-of-the-box."

Our combined file right now is less than 400 lines.  It's around 200 lines right now and I don't expect it to blow up.  I think we do have the risk of breaking the whole thing when editing one piece right now.. which is why we need to build some tests.

**Comment by Wavfact** [comment]
We install via bower and had to modify our bower file to only accept 1.1.1.. Once I went back, everything was fine.. Being combined vs multiple component files doesn't really make a difference, it all still has to get loaded.. and with all the other multi-file bower components, its best to support coding standards than save a millisecond on loading..  just my unqualified opinion.. ;)

**Comment by tygavin** [comment]
I do appreciate the discussion and feedback.

In addition to milliseconds saved by removing the 2 extra HTTP requests, I think ease of implementation is also important consideration.  The html page now has only one .js file to include in order to add the Tealium Angular JS integration component.  Right now, these factors have a slight edge over development modularity.  

The modularity argument has stronger footing with more code and more complexity.  If this thing were bigger and if we do pass the 400 lines of code guideline, then I think we'll need another round of refactoring or potentially move to multiple files to help with the development and maintenance.  I'm actually hoping the number of lines of code decreases moving forward.  We'll see..

**Comment by ysterbal** [comment]
This is an interesting approach the to problem, I would have thought modularity from a development perspective would be considered preferable, no matter the no of lines code. Bundling could be dealt with as a separate step to allow for compression, obfuscation or any other optimization. 

You could leave the packaging of the module up to the users, if they feel 2 HTTP Requests and a couple of milliseconds matter they can utilize something like **grunt-bower-concat** to repackage the components to optimize for deployment. 

I just think this is a little too early for this kind of optimization. 

My two cents for what it is worth.

**Comment by tygavin** [comment]
I think that's true that we should expect the files to be combined either way at deploy time via grunt.

**Comment by tygavin** [comment]
I'm going to end the debate by closing this thread.  

My expectation is more people will want to use this component as opposed to develop or maintain it.  In the short term, we're going to use one file until this file becomes large or too complex for a developer to maintain.

For reference, related conversation here: https://github.com/Tealium/integration-angularjs/issues/12

**Comment by Wavfact** [comment]
I'll take this up with Tealium as it broke our site..  We are one of the largest retail companies using Tealium, this answer is unacceptable. While I do agree progress is always the path forward, but only when tested and hardened for production usage.  I do not think it is Tealium's policy to put untested code out for their customers based on one person's expectations..

**Comment by tygavin** [comment]
@Wavfact The code is manually tested right now.  We just don't have automated tests built-in yet.

My understanding is your internal test cases detected the code change and failed.  This is great that you were able to catch this before going live, but I understand this is not ideal as it is an unexpected change.  

The code has changed significantly in recent releases. Recently we have had multiple contributors make some fairly significant changes by adding the "bower.json," refactoring to use provider pattern, and adding strict dependency injection support.

My expectation is once you are updated to include the new combined .js file in your code you will be able to use the latest release.  If you are able to reproduce a bug in the latest release (using the "sample" app), please let me know.
